### ISSUE TITLE
KeyError occurs when training

### ISSUE THREAD

**Issue by infinite-optimization** [fengtuan/DML_SS#1]
Hi, sir

KeyError occurs in every training command, how should I fix it?

thank you!

**Comment by infinite-optimization** [comment]
~: bash train.sh
Starting training...
Traceback (most recent call last):
  File "/code/DML_SS/train_hybrid_feature.py", line 72, in <module>
    train_list,valid_list,test_list = Load_DataSet(args.dataset,EncodingType.pssm_hhm_phys,isEightClass)
  File "/code/DML_SS/datasets/dataset.py", line 211, in Load_DataSet
    return CB513(encodingType,isEightClass)
  File "/code/DML_SS/datasets/dataset.py", line 157, in CB513
    Data=Load_H5PY('data/hybrid/PISCES_Data',encodingType,isEightClass,dataset='CB513')
  File "/code/DML_SS/datasets/dataset.py", line 100, in Load_H5PY
    PrimarySeq=[AA_Dict[e] for e in PrimarySeq]
  File "/code/DML_SS/datasets/dataset.py", line 100, in <listcomp>
    PrimarySeq=[AA_Dict[e] for e in PrimarySeq]
KeyError: 77
Starting training...
...
    PrimarySeq=[AA_Dict[e] for e in PrimarySeq]
KeyError: 77
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 83
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 77
Starting training...
...
KeyError: 83

**Comment by infinite-optimization** [comment]
It seems that it a encoding bug of Python. Uncomment the code like ProteinID=ProteinID.decode() is helpful.
